set-option -g default-shell /usr/bin/fish

# Copy Mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Editor
set-option -sg escape-time 10

# Indexing
set-option -g base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Interface (misc)
set-option -g display-time 2000
set-option -g focus-events on
set-option -g history-limit 50000
set-option -g set-clipboard on

# Mouse
set-option -g mouse on
bind-key m set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

# Prefix
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# Splits
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Status Bar
set-option -g status-position top
set-option -g status-interval 5
set-option -g status-style 'bg=default fg=#d65d0e'
set-option -g pane-active-border-style 'fg=#458588'
set-option -g pane-border-style 'fg=#3c3836'
set-option -g window-status-current-style 'fg=#d79921 bold'
set-option -g window-status-style 'fg=#a89984'

# Terminal features
set-option -as terminal-features '*:RGB:clipboard:usstyle:sync:hyperlinks:cstyle:ccolour:focus:title:osc7'
set-option -as terminal-features '*kitty*:sixel'
set-option -as terminal-features '*ghostty*:sixel'
set-option -as terminal-features 'wezterm:sixel'

# TPM
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-continuum'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'christoomey/vim-tmux-navigator'

set-option -g @continuum-restore 'on'
set-option -g @continuum-save-interval '15'

set-option -g @resurrect-hook-post-save-all 'find ~/.local/share/tmux/resurrect/ -name "tmux_resurrect_*.txt" -mtime +30 -delete'

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'
