sensors:
 - chip: thinkpad-isa-0000
   ids: [ CPU, GPU ]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0, 0, 50]
  - ["level auto", 45, 70]
  - ["level 7", 65, 80]
  - ["level disengaged", 75, 255]
